// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGAPhMDYYxIOWuCQsK9mtDTHcX1RDtO0',
    appId: '1:38999013244:web:df834303ce3fc65a7f96f9',
    messagingSenderId: '38999013244',
    projectId: 'twitter-clone-8fb71',
    authDomain: 'twitter-clone-8fb71.firebaseapp.com',
    storageBucket: 'twitter-clone-8fb71.firebasestorage.app',
    measurementId: 'G-3MM9RHTV6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkm66GO-RTJ_Bt_1UENVSKQgd7U1miag',
    appId: '1:38999013244:android:6d9792305346d9207f96f9',
    messagingSenderId: '38999013244',
    projectId: 'twitter-clone-8fb71',
    storageBucket: 'twitter-clone-8fb71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfjdZVHIbzyCommtfnEz8lZvqnWH3vNM',
    appId: '1:38999013244:ios:0c0a36a4526a98e97f96f9',
    messagingSenderId: '38999013244',
    projectId: 'twitter-clone-8fb71',
    storageBucket: 'twitter-clone-8fb71.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );
}
